import mongoose from "mongoose";

export const medicines = [
  {
    name: "Amoxil",
    genericName: "Amoxicillin",
    brand: "Amoxil",
    manufacturer: "GSK Pharmaceuticals",
    category: "antibiotic",
    subcategory: "penicillin",
    dosageForms: [
      { form: "capsule", strength: "250", unit: "mg" },
      { form: "capsule", strength: "500", unit: "mg" },
    ],
    composition: [
      { ingredient: "Amoxicillin Trihydrate", strength: "500", unit: "mg" },
    ],
    prescriptionRequired: true,
    schedule: "schedule-h",
    description: "Broad spectrum penicillin antibiotic.",
    indications: ["Respiratory infections", "UTI", "Skin infections"],
    sideEffects: ["Diarrhea", "Allergic reaction"],
    dosageInstructions: "As prescribed by physician.",
    storageInstructions: "Store below 25°C.",
    shelfLife: 36,
    images: [{ url: "/uploads/medicines/amoxil-capsule.jpg" }],
    barcodes: ["8904567890123"],
    regulatoryInfo: {
      drugLicenseNumber: "DL-MH-2018-9821",
      approvalDate: new Date("2014-03-15"),
      fdaApproved: true,
    },
    tags: ["antibiotic", "amoxicillin"],
    status: "active",
    metadata: {
      createdBy: new mongoose.Types.ObjectId("694e506ebe97d77644600200"),
      verified: true,
      verificationDate: new Date(),
    },
  },
  {
    name: "Azithral",
    genericName: "Azithromycin",
    brand: "Azithral 500",
    manufacturer: "Alembic Pharmaceuticals",
    category: "antibiotic",
    dosageForms: [{ form: "tablet", strength: "500", unit: "mg" }],
    composition: [{ ingredient: "Azithromycin", strength: "500", unit: "mg" }],
    prescriptionRequired: true,
    schedule: "schedule-h",
    images: [{ url: "/uploads/medicines/azithral-tablet.jpg" }],
    barcodes: ["8904567890124"],
    regulatoryInfo: {
      drugLicenseNumber: "DL-GJ-2020-3311",
      approvalDate: new Date("2013-01-10"),
      fdaApproved: true,
    },
    tags: ["antibiotic"],
    status: "active",
    metadata: {
      createdBy: new mongoose.Types.ObjectId("694e506ebe97d77644600200"),
      verified: true,
      verificationDate: new Date(),
    },
  },
  {
    name: "Cetzine",
    genericName: "Cetirizine Hydrochloride",
    brand: "Cetzine",
    manufacturer: "Dr. Reddy’s Laboratories",
    category: "antihistamine",
    subcategory: "allergy",
    dosageForms: [
      { form: "tablet", strength: "10", unit: "mg" },
      { form: "syrup", strength: "5/5", unit: "ml" },
    ],
    composition: [
      { ingredient: "Cetirizine Hydrochloride", strength: "10", unit: "mg" },
    ],
    prescriptionRequired: false,
    schedule: "otc",
    description:
      "Relieves allergy symptoms like sneezing, itching and runny nose.",
    indications: ["Allergic rhinitis", "Urticaria"],
    sideEffects: ["Drowsiness", "Dry mouth"],
    dosageInstructions: "Once daily or as advised.",
    storageInstructions: "Store below 30°C.",
    shelfLife: 36,
    images: [
      { url: "/uploads/medicines/cetzine-tablet.jpg" },
      { url: "/uploads/medicines/cetzine-syrup.jpg" },
    ],
    barcodes: ["8904567890125"],
    regulatoryInfo: {
      drugLicenseNumber: "DL-TN-2019-2211",
      approvalDate: new Date("2012-04-15"),
      fdaApproved: true,
    },
    tags: ["allergy", "antihistamine"],
    status: "active",
    metadata: {
      createdBy: new mongoose.Types.ObjectId("694e506ebe97d77644600200"),
      verified: true,
      verificationDate: new Date(),
    },
  },

  {
    name: "Glycomet",
    genericName: "Metformin",
    brand: "Glycomet",
    manufacturer: "USV Pvt Ltd",
    category: "antidiabetic",
    subcategory: "biguanide",
    dosageForms: [
      { form: "tablet", strength: "500", unit: "mg" },
      { form: "tablet", strength: "1000", unit: "mg" },
    ],
    composition: [
      { ingredient: "Metformin Hydrochloride", strength: "500", unit: "mg" },
    ],
    prescriptionRequired: true,
    schedule: "schedule-h",
    description: "Controls blood sugar levels in type 2 diabetes.",
    indications: ["Type 2 Diabetes"],
    sideEffects: ["Nausea", "Diarrhea"],
    dosageInstructions: "Take with meals as prescribed.",
    storageInstructions: "Store below 25°C.",
    shelfLife: 48,
    images: [{ url: "/uploads/medicines/glycomet-tablet.jpg" }],
    barcodes: ["8904567890126"],
    regulatoryInfo: {
      drugLicenseNumber: "DL-MH-2017-7744",
      approvalDate: new Date("2011-08-20"),
      fdaApproved: true,
    },
    tags: ["diabetes", "metformin"],
    status: "active",
    metadata: {
      createdBy: new mongoose.Types.ObjectId("694e506ebe97d77644600200"),
      verified: true,
      verificationDate: new Date(),
    },
  },

  {
    name: "Amlodac",
    genericName: "Amlodipine",
    brand: "Amlodac",
    manufacturer: "Zydus Cadila",
    category: "antihypertensive",
    subcategory: "calcium-channel-blocker",
    dosageForms: [
      { form: "tablet", strength: "5", unit: "mg" },
      { form: "tablet", strength: "10", unit: "mg" },
    ],
    composition: [
      { ingredient: "Amlodipine Besylate", strength: "5", unit: "mg" },
    ],
    prescriptionRequired: true,
    schedule: "schedule-h",
    description: "Used to treat high blood pressure and angina.",
    indications: ["Hypertension", "Angina"],
    sideEffects: ["Swelling of ankles", "Dizziness"],
    dosageInstructions: "Once daily or as prescribed.",
    storageInstructions: "Store below 30°C.",
    shelfLife: 48,
    images: [{ url: "/uploads/medicines/amodac-tablet.jpg" }],
    barcodes: ["8904567890127"],
    regulatoryInfo: {
      drugLicenseNumber: "DL-GJ-2016-4488",
      approvalDate: new Date("2010-11-12"),
      fdaApproved: true,
    },
    tags: ["hypertension", "cardiac"],
    status: "active",
    metadata: {
      createdBy: new mongoose.Types.ObjectId("694e506ebe97d77644600200"),
      verified: true,
      verificationDate: new Date(),
    },
  },

  {
    name: "Pantocid",
    genericName: "Pantoprazole",
    brand: "Pantocid 40",
    manufacturer: "Sun Pharmaceutical Industries",
    category: "gastrointestinal",
    subcategory: "proton-pump-inhibitor",
    dosageForms: [{ form: "tablet", strength: "40", unit: "mg" }],
    composition: [
      { ingredient: "Pantoprazole Sodium", strength: "40", unit: "mg" },
    ],
    prescriptionRequired: true,
    schedule: "schedule-h",
    description: "Reduces stomach acid production.",
    indications: ["GERD", "Acidity"],
    sideEffects: ["Headache", "Diarrhea"],
    dosageInstructions: "Once daily before meals.",
    storageInstructions: "Store below 25°C.",
    shelfLife: 36,
    images: [{ url: "/uploads/medicines/pantocid-tablet.jpg" }],
    barcodes: ["8904567890128"],
    regulatoryInfo: {
      drugLicenseNumber: "DL-MH-2019-3344",
      approvalDate: new Date("2012-05-19"),
      fdaApproved: true,
    },
    tags: ["acid", "gerd"],
    status: "active",
    metadata: {
      createdBy: new mongoose.Types.ObjectId("694e506ebe97d77644600200"),
      verified: true,
      verificationDate: new Date(),
    },
  },

  {
    name: "Asthalin",
    genericName: "Salbutamol",
    brand: "Asthalin Inhaler",
    manufacturer: "Cipla Ltd",
    category: "respiratory",
    subcategory: "bronchodilator",
    dosageForms: [{ form: "inhaler", strength: "100", unit: "mcg" }],
    composition: [{ ingredient: "Salbutamol", strength: "100", unit: "mcg" }],
    prescriptionRequired: true,
    schedule: "schedule-h",
    description: "Provides relief from asthma and bronchospasm.",
    indications: ["Asthma", "COPD"],
    sideEffects: ["Tremors", "Palpitations"],
    dosageInstructions: "Use as directed by physician.",
    storageInstructions: "Store below 30°C.",
    shelfLife: 24,
    images: [{ url: "/uploads/medicines/asthalin-inhaler.jpg" }],
    barcodes: ["8904567890129"],
    regulatoryInfo: {
      drugLicenseNumber: "DL-MH-2018-9911",
      approvalDate: new Date("2009-07-21"),
      fdaApproved: true,
    },
    tags: ["asthma", "respiratory"],
    status: "active",
    metadata: {
      createdBy: new mongoose.Types.ObjectId("694e506ebe97d77644600200"),
      verified: true,
      verificationDate: new Date(),
    },
  },

  {
    name: "Betnovate",
    genericName: "Betamethasone",
    brand: "Betnovate-N",
    manufacturer: "GSK India",
    category: "dermatological",
    subcategory: "steroid",
    dosageForms: [
      { form: "cream", strength: "0.1", unit: "%" },
      { form: "ointment", strength: "0.1", unit: "%" },
    ],
    composition: [
      { ingredient: "Betamethasone Valerate", strength: "0.1", unit: "%" },
    ],
    prescriptionRequired: true,
    schedule: "schedule-h",
    description: "Used to treat inflammatory skin conditions.",
    indications: ["Eczema", "Dermatitis"],
    sideEffects: ["Skin irritation"],
    dosageInstructions: "Apply thin layer once or twice daily.",
    storageInstructions: "Store below 25°C.",
    shelfLife: 24,
    images: [{ url: "/uploads/medicines/betnovate-cream.jpg" }],
    barcodes: ["8904567890130"],
    regulatoryInfo: {
      drugLicenseNumber: "DL-AP-2020-5577",
      approvalDate: new Date("2011-09-05"),
      fdaApproved: true,
    },
    tags: ["skin", "steroid"],
    status: "active",
    metadata: {
      createdBy: new mongoose.Types.ObjectId("694e506ebe97d77644600200"),
      verified: true,
      verificationDate: new Date(),
    },
  },

  {
    name: "Electral",
    genericName: "Oral Rehydration Salts",
    brand: "Electral",
    manufacturer: "FDC Ltd",
    category: "supplement",
    subcategory: "electrolytes",
    dosageForms: [{ form: "powder", strength: "21", unit: "g" }],
    composition: [
      { ingredient: "Glucose + Electrolytes", strength: "21", unit: "g" },
    ],
    prescriptionRequired: false,
    schedule: "otc",
    description: "Prevents dehydration due to diarrhea and vomiting.",
    indications: ["Dehydration", "Diarrhea"],
    sideEffects: ["Nausea (rare)"],
    dosageInstructions: "Dissolve in 1 litre of water.",
    storageInstructions: "Store in cool dry place.",
    shelfLife: 24,
    images: [{ url: "/uploads/medicines/electral-powder.jpg" }],
    barcodes: ["8904567890131"],
    regulatoryInfo: {
      drugLicenseNumber: "DL-MH-2016-1100",
      approvalDate: new Date("2008-02-18"),
      fdaApproved: true,
    },
    tags: ["ors", "dehydration"],
    status: "active",
    metadata: {
      createdBy: new mongoose.Types.ObjectId("694e506ebe97d77644600200"),
      verified: true,
      verificationDate: new Date(),
    },
  },

  {
    name: "Liv 52",
    genericName: "Herbal Liver Tonic",
    brand: "Liv 52",
    manufacturer: "Himalaya Wellness",
    category: "herbal",
    subcategory: "liver-care",
    dosageForms: [
      { form: "tablet", strength: "260", unit: "mg" },
      { form: "syrup", strength: "5/5", unit: "ml" },
    ],
    composition: [
      { ingredient: "Herbal Extracts", strength: "260", unit: "mg" },
    ],
    prescriptionRequired: false,
    schedule: "otc",
    description: "Supports liver function and detoxification.",
    indications: ["Liver disorders", "Loss of appetite"],
    sideEffects: ["Rare gastrointestinal upset"],
    dosageInstructions: "Twice daily after meals.",
    storageInstructions: "Store below 30°C.",
    shelfLife: 36,
    images: [
      { url: "/uploads/medicines/liv52-tablet.jpg" },
      { url: "/uploads/medicines/liv52-syrup.jpg" },
    ],
    barcodes: ["8904567890132"],
    regulatoryInfo: {
      drugLicenseNumber: "AYU-KA-2015-7788",
      approvalDate: new Date("2005-06-12"),
      fdaApproved: false,
    },
    tags: ["herbal", "liver"],
    status: "active",
    metadata: {
      createdBy: new mongoose.Types.ObjectId("694e506ebe97d77644600200"),
      verified: true,
      verificationDate: new Date(),
    },
  },
];
